const CACHE_NAME = 'jerk-tracker-v1.0.0';
const STATIC_CACHE = 'jerk-tracker-static-v1.0.0';
const DYNAMIC_CACHE = 'jerk-tracker-dynamic-v1.0.0';

// Static assets to cache immediately
const STATIC_ASSETS = [
  '/',
  '/admin',
  '/order',
  '/pricing',
  '/how-it-works',
  '/qr-tracking',
  '/offline.html',
  '/manifest.json',
  // Add your CSS and JS bundles here (they'll be generated by Next.js)
];

// GitHub API and other external resources to cache
const CACHEABLE_ORIGINS = [
  'https://api.github.com',
  'https://fonts.googleapis.com',
  'https://fonts.gstatic.com',
  'https://cdn.jsdelivr.net'
];

// Install event - cache static assets
self.addEventListener('install', (event) => {
  console.log('[SW] Installing service worker');
  
  event.waitUntil(
    (async () => {
      try {
        const staticCache = await caches.open(STATIC_CACHE);
        console.log('[SW] Caching static assets');
        await staticCache.addAll(STATIC_ASSETS);
        
        // Force activation of new service worker
        await self.skipWaiting();
      } catch (error) {
        console.error('[SW] Failed to cache static assets:', error);
      }
    })()
  );
});

// Activate event - cleanup old caches
self.addEventListener('activate', (event) => {
  console.log('[SW] Activating service worker');
  
  event.waitUntil(
    (async () => {
      // Clean up old caches
      const cacheNames = await caches.keys();
      const deletePromises = cacheNames
        .filter(name => name !== STATIC_CACHE && name !== DYNAMIC_CACHE)
        .map(name => {
          console.log('[SW] Deleting old cache:', name);
          return caches.delete(name);
        });
      
      await Promise.all(deletePromises);
      
      // Take control of all clients
      await self.clients.claim();
    })()
  );
});

// Fetch event - serve cached content or fetch from network
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);
  
  // Skip non-GET requests
  if (request.method !== 'GET') {
    return;
  }
  
  // Skip chrome-extension requests
  if (url.protocol === 'chrome-extension:') {
    return;
  }
  
  event.respondWith(handleFetch(request));
});

async function handleFetch(request) {
  const url = new URL(request.url);
  
  try {
    // Strategy 1: Static assets - Cache First
    if (STATIC_ASSETS.some(asset => url.pathname === asset || url.pathname.startsWith(asset))) {
      return await cacheFirst(request, STATIC_CACHE);
    }
    
    // Strategy 2: API requests - Network First with GitHub API caching
    if (url.pathname.startsWith('/api/') || CACHEABLE_ORIGINS.includes(url.origin)) {
      return await networkFirst(request, DYNAMIC_CACHE);
    }
    
    // Strategy 3: Navigation requests - Network First with offline fallback
    if (request.mode === 'navigate') {
      return await networkFirstWithOfflineFallback(request);
    }
    
    // Strategy 4: Other resources - Stale While Revalidate
    return await staleWhileRevalidate(request, DYNAMIC_CACHE);
    
  } catch (error) {
    console.error('[SW] Fetch error:', error);
    
    // Return offline page for navigation requests
    if (request.mode === 'navigate') {
      const cache = await caches.open(STATIC_CACHE);
      return await cache.match('/offline.html') || new Response('Offline');
    }
    
    return new Response('Network error', { status: 503 });
  }
}

// Cache strategies
async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  
  if (cached) {
    return cached;
  }
  
  const response = await fetch(request);
  
  if (response.status === 200) {
    cache.put(request, response.clone());
  }
  
  return response;
}

async function networkFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  
  try {
    const response = await fetch(request);
    
    if (response.status === 200) {
      // Cache successful GitHub API responses for offline access
      if (request.url.includes('api.github.com')) {
        cache.put(request, response.clone());
      }
    }
    
    return response;
  } catch (error) {
    console.log('[SW] Network failed, trying cache:', request.url);
    const cached = await cache.match(request);
    
    if (cached) {
      return cached;
    }
    
    throw error;
  }
}

async function networkFirstWithOfflineFallback(request) {
  try {
    const response = await fetch(request);
    
    // Cache successful navigation responses
    if (response.status === 200) {
      const cache = await caches.open(DYNAMIC_CACHE);
      cache.put(request, response.clone());
    }
    
    return response;
  } catch (error) {
    // Try cache first
    const cache = await caches.open(DYNAMIC_CACHE);
    const cached = await cache.match(request);
    
    if (cached) {
      return cached;
    }
    
    // Return offline page
    const staticCache = await caches.open(STATIC_CACHE);
    return await staticCache.match('/offline.html') || new Response('Offline');
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  
  // Start fetching in background
  const fetchPromise = fetch(request).then(response => {
    if (response.status === 200) {
      cache.put(request, response.clone());
    }
    return response;
  }).catch(() => {
    // Ignore fetch errors for stale-while-revalidate
  });
  
  // Return cached version immediately if available
  if (cached) {
    // Don't await the fetch promise to return cached content immediately
    fetchPromise;
    return cached;
  }
  
  // If no cache, wait for network
  return await fetchPromise;
}

// Background sync for GitHub integration
self.addEventListener('sync', (event) => {
  console.log('[SW] Background sync:', event.tag);
  
  if (event.tag === 'github-sync') {
    event.waitUntil(syncGitHubData());
  }
});

async function syncGitHubData() {
  try {
    console.log('[SW] Syncing GitHub data in background');
    
    // Get pending GitHub operations from IndexedDB or localStorage
    // This would sync any offline changes when connection is restored
    const pendingOperations = await getPendingOperations();
    
    for (const operation of pendingOperations) {
      try {
        await performGitHubOperation(operation);
        await removePendingOperation(operation.id);
      } catch (error) {
        console.error('[SW] Failed to sync operation:', operation, error);
      }
    }
  } catch (error) {
    console.error('[SW] Background sync failed:', error);
  }
}

// Push notifications for order updates
self.addEventListener('push', (event) => {
  console.log('[SW] Push notification received');
  
  const options = {
    body: 'New order update available',
    icon: '/icons/icon-192x192.png',
    badge: '/icons/icon-96x96.png',
    vibrate: [200, 100, 200],
    data: {
      dateOfArrival: Date.now(),
      primaryKey: 1
    },
    actions: [
      {
        action: 'view',
        title: 'View Order',
        icon: '/icons/action-view.png'
      },
      {
        action: 'close',
        title: 'Close',
        icon: '/icons/action-close.png'
      }
    ]
  };
  
  if (event.data) {
    const data = event.data.json();
    options.body = data.message || options.body;
    options.data = { ...options.data, ...data };
  }
  
  event.waitUntil(
    self.registration.showNotification('JERK Tracker', options)
  );
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification clicked:', event.action);
  
  event.notification.close();
  
  if (event.action === 'view') {
    event.waitUntil(
      self.clients.openWindow('/admin')
    );
  } else if (event.action === 'close') {
    // Just close the notification
  } else {
    // Default action - open the app
    event.waitUntil(
      self.clients.openWindow('/')
    );
  }
});

// Placeholder functions for GitHub sync (implement based on your data storage)
async function getPendingOperations() {
  // Implement: Get pending operations from storage
  return [];
}

async function performGitHubOperation(operation) {
  // Implement: Perform the GitHub API operation
  console.log('Performing operation:', operation);
}

async function removePendingOperation(operationId) {
  // Implement: Remove completed operation from storage
  console.log('Removing operation:', operationId);
}

console.log('[SW] Service worker loaded successfully');